import { MovieSchema } from '../interfaces/apiInterface';

export const dummyOverview = "A movie criticism is written by a scholar or expert in film studies to discuss the movie within a historical, social, political, or theoretical context. It differs from the opinion or recommendation that a movie review provides in terms of length, content and focus. Criticisms can be found in cinema studies journals as well as discipline-specific sources, depending on the plot or themes of the movie."

export const dummyArr:MovieSchema[] = [
  {
    adult: false,
    backdrop_path: "/hUVJVsKP7Fu2kGdWXZKbEAXRMNM.jpg",
    genre_ids: [35, 28, 14],
    id: 594767,
    original_language: "en",
    original_title: "Shazam! Fury of the Gods",
    overview:
      'Billy Batson and his foster siblings, who transform into superheroes by saying "Shazam!", are forced to get back into action and fight the Daughters of Atlas, who they must stop from using a weapon that could destroy the world.',
    popularity: 587.013,
    poster_path: "/A3ZbZsmsvNGdprRi2lKgGEeVLEH.jpg",
    release_date: "2023-03-15",
    title: "Shazam! Fury of the Gods",
    video: false,
    vote_average: 6.703,
    vote_count: 2000,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [35],
    id: 197806,
    original_language: "en",
    original_title: "God",
    overview:
      "Talking to the camera, Margaret tells us about her friendship with God. \"We talk every day,\" she explains. And at that moment, her phone rings, and it's God on the line. God's gossip is the best, Margaret tells us. Then, we see what happens to her when she and God have a falling out. Can they patch it up? Is she sane?",
    popularity: 1.675,
    poster_path: "/la0eOA49YtQfffTwQFFFVIJCh5u.jpg",
    release_date: "1998-01-01",
    title: "God",
    video: false,
    vote_average: 6.643,
    vote_count: 7,
  },
  {
    adult: false,
    backdrop_path: "/m1yUEkEN3OWVxAKgDESWnIGyxHh.jpg",
    genre_ids: [18],
    id: 712698,
    original_language: "en",
    original_title: "God",
    overview:
      'Submersed in "bro" culture, a fraternity brother\'s obsession with a poem and its poetess begin to inform him more about himself than he is ready to accept.',
    popularity: 0.6,
    poster_path: "/3AAhmZthxBdkLfuIEDrTc8O49xo.jpg",
    release_date: "2019-08-28",
    title: "God",
    video: false,
    vote_average: 4.429,
    vote_count: 7,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [18],
    id: 494892,
    original_language: "en",
    original_title: "God",
    overview:
      "A psych-drama-thriller combo that tackles shady politicians, leaked documents and a lack of enthusiasm for religion.",
    popularity: 0.6,
    poster_path: "/4np8KzfT7XHgwQT5sJTRogqIn0s.jpg",
    release_date: "2016-12-29",
    title: "God",
    video: false,
    vote_average: 8.429,
    vote_count: 7,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [],
    id: 516754,
    original_language: "en",
    original_title: "GOD",
    overview: "Game of Death - Bruce Lee Cut",
    popularity: 0.9,
    poster_path: null,
    release_date: "",
    title: "GOD",
    video: false,
    vote_average: 10,
    vote_count: 2,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [99],
    id: 763789,
    original_language: "pt",
    original_title: "GOD",
    overview: "Work by Sofia Caetano.",
    popularity: 0.6,
    poster_path: "/odqmePV6EqJ3DFpZ8WWXT18Mxhv.jpg",
    release_date: "2017-12-16",
    title: "GOD",
    video: false,
    vote_average: 1.5,
    vote_count: 2,
  },
  {
    adult: false,
    backdrop_path: "/q3j4OQFFDKM6fdQt9gE56kfDBNG.jpg",
    genre_ids: [16, 878, 28, 12],
    id: 536115,
    original_language: "ja",
    original_title: "GODZILLA 星を喰う者",
    overview:
      "With no means for defeating Godzilla Earth, mankind watches as King Ghidorah, clad in a golden light, descends on the planet. The heavens and earth shake once again as the war moves to a higher dimension.",
    popularity: 22.529,
    poster_path: "/fOA44BITFth0u4hMSOUgpK0kM6t.jpg",
    release_date: "2018-11-09",
    title: "Godzilla: The Planet Eater",
    video: false,
    vote_average: 6.46,
    vote_count: 263,
  },
  {
    adult: false,
    backdrop_path: "/yIDS5QLvKtgzfu43eUWx5JkGW6p.jpg",
    genre_ids: [16, 28, 878],
    id: 126963,
    original_language: "ja",
    original_title: "ドラゴンボールZ 神と神",
    overview:
      'The events of Battle of Gods take place some years after the battle with Majin Buu, which determined the fate of the entire universe. After awakening from a long slumber, Beerus, the God of Destruction is visited by Whis, his attendant and learns that the galactic overlord Frieza has been defeated by a Super Saiyan from the North Quadrant of the universe named Goku, who is also a former student of the North Kai. Ecstatic over the new challenge, Goku ignores King Kai\'s advice and battles Beerus, but he is easily overwhelmed and defeated. Beerus leaves, but his eerie remark of "Is there nobody on Earth more worthy to destroy?" lingers on. Now it is up to the heroes to stop the God of Destruction before all is lost.',
    popularity: 54.237,
    poster_path: "/nxZEdYcHMuD8SSuwusDnK9CD2H1.jpg",
    release_date: "2013-03-30",
    title: "Dragon Ball Z: Battle of Gods",
    video: false,
    vote_average: 6.802,
    vote_count: 1363,
  },
  {
    adult: false,
    backdrop_path: "/61zVzhJ1BnvYiC7THoLf4jyrxBw.jpg",
    genre_ids: [80, 18],
    id: 73475,
    original_language: "de",
    original_title: "Der Ruf der blonden Göttin",
    overview:
      "Susan arrives in Haiti to live with her husband Jack, who lives with a lesbian housekeeper and Olga, a nymphomaniac platinum blonde, introduced to her as Jack's sister. Susan begins to have nightmares about voodoo ceremonies and murder.",
    popularity: 32.061,
    poster_path: "/4M1TMBzg9FZvRQkvcf8nQLSclu5.jpg",
    release_date: "1977-12-09",
    title: "Call of the Blonde Goddess",
    video: false,
    vote_average: 4.806,
    vote_count: 31,
  },
  {
    adult: false,
    backdrop_path: "/mu4q1jPLdW5hE7BWZEWRvuAh3ZN.jpg",
    genre_ids: [16, 878],
    id: 492719,
    original_language: "ja",
    original_title: "GODZILLA 決戦機動増殖都市",
    overview:
      "Humanity's desperate battle to reclaim the Earth from Godzilla continues. The key to defeating the King of the Monsters may be Mechagodzilla, a robotic weapon thought to have been lost nearly 20,000 years ago.",
    popularity: 16.581,
    poster_path: "/8y1YhD6niL3aMfeEPhStHMWdPxH.jpg",
    release_date: "2018-05-18",
    title: "Godzilla: City on the Edge of Battle",
    video: false,
    vote_average: 6.468,
    vote_count: 278,
  },
  {
    adult: false,
    backdrop_path: "/cpcDNWL2OgtCCcH7DDRjY8oxUsn.jpg",
    genre_ids: [53, 18],
    id: 880313,
    original_language: "es",
    original_title: "La ira de Dios",
    overview:
      "Convinced the tragic deaths of her loved ones were orchestrated by a famous novelist she worked for, Luciana turns to a journalist to expose her truth.",
    popularity: 23.867,
    poster_path: "/lFhxNXEK0UpXXqSbhba83Zhl2uk.jpg",
    release_date: "2022-06-15",
    title: "The Wrath of God",
    video: false,
    vote_average: 6.4,
    vote_count: 161,
  },
  {
    adult: false,
    backdrop_path: "/5p3aTxtUtZHCHwYsuycutmxIhND.jpg",
    genre_ids: [18, 80],
    id: 598,
    original_language: "pt",
    original_title: "Cidade de Deus",
    overview:
      "In the slums of Rio, two kids' paths diverge as one struggles to become a photographer and the other a kingpin.",
    popularity: 38.897,
    poster_path: "/k7eYdWvhYQyRQoU2TB2A2Xu2TfD.jpg",
    release_date: "2002-08-30",
    title: "City of God",
    video: false,
    vote_average: 8.423,
    vote_count: 6518,
  },
  {
    adult: false,
    backdrop_path: "/5QAc8dsyOwJBGQ71mhOLMEivOsF.jpg",
    genre_ids: [16, 28, 878],
    id: 449574,
    original_language: "ja",
    original_title: "GODZILLA 怪獣惑星",
    overview:
      "A desperate group of refugees attempts to recolonize Earth 20,000 years after Godzilla took over. But one young man wants revenge above all else.",
    popularity: 16.318,
    poster_path: "/hAuZ7g6TqDLv5fOqXIPgYRguOkm.jpg",
    release_date: "2017-11-17",
    title: "Godzilla: Planet of the Monsters",
    video: false,
    vote_average: 6.318,
    vote_count: 414,
  },
  {
    adult: false,
    backdrop_path: "/q4k9UDHE5foTcs48zpqJbpLUDNU.jpg",
    genre_ids: [28, 16, 14],
    id: 83090,
    original_language: "ja",
    original_title: "聖闘士星矢",
    overview:
      "When Seiya, Hyōga and Shun visit Saori (Athena) at the orphanage, they meet an employee called Eri. An orphan herself, Eri takes a liking to Hyōga and one night they sit outside watching the stars. They see a shooting star and Hyōga asks Eri to make a wish. After Hyōga leaves, however, Eri becomes powerfully attracted to the shooting star and wanders alone into the woods, where she finds a golden apple. She is then possessed by Eris, the Goddess of Discord, and kidnaps Athena, planning to use the golden apple to suck her energy out, fully reincarnate and take over the world. Eris leaves a message for the Bronze Saints, who set out for the goddess's temple which appears on the mountains. There, the heroes fight the five Ghost Saints: Maya of Sagitta, Orpheus of Lyra, Christ of the Southern Cross, Jan of Scutum (called by the Japanese name Tateza) and Jäger of Orion.",
    popularity: 50.496,
    poster_path: "/44Ni4sNvXkyRAh2ayuE07CV0lE5.jpg",
    release_date: "1987-07-18",
    title: "Saint Seiya: Evil Goddess Eris",
    video: false,
    vote_average: 7.091,
    vote_count: 181,
  },
  {
    adult: false,
    backdrop_path: "/wqpTrmGiqMJ6onAq3zrBhfomIJl.jpg",
    genre_ids: [16, 12, 35, 14],
    id: 532067,
    original_language: "ja",
    original_title: "映画 この素晴らしい世界に祝福を！紅伝説",
    overview:
      "It is not strange that the Demon Lord's forces fear the Crimson Demons, the clan from which Megumin and Yunyun originate. Even if the Demon Lord's generals attack their village, the Crimson Demons can just easily brush them off with their supreme mastery of advanced and overpowered magic.  When Yunyun receives a seemingly serious letter regarding a potential disaster coming to her hometown, she immediately informs Kazuma Satou and the rest of his party. After a series of wacky misunderstandings, it turns out to be a mere prank by her fellow demon who wants to be an author. Even so, Megumin becomes worried about her family and sets out toward the Crimson Demons' village with the gang.  There, Kazuma and the others decide to sightsee the wonders of Megumin's birthplace. However, they soon come to realize that the nonsense threat they received might have been more than just a joke.",
    popularity: 30.015,
    poster_path: "/fv5BgcfkpWh3V6Pb1qVlXESBOdl.jpg",
    release_date: "2019-08-30",
    title:
      "KONOSUBA – God's blessing on this wonderful world! Legend of Crimson",
    video: false,
    vote_average: 8.159,
    vote_count: 466,
  },
  {
    adult: false,
    backdrop_path: "/b1L7qevxiVpkVFq4dmdQPGFPWH0.jpg",
    genre_ids: [27],
    id: 836225,
    original_language: "en",
    original_title: "The Exorcism of God",
    overview:
      "An American priest working in Mexico is considered a saint by many local parishioners. However, due to a botched exorcism, he carries a secret that’s eating him alive until he gets an opportunity to face his demon one final time.",
    popularity: 85.573,
    poster_path: "/9X9wKbF0ED1AQpgIkvq0MG4Y4wi.jpg",
    release_date: "2022-03-11",
    title: "The Exorcism of God",
    video: false,
    vote_average: 7.161,
    vote_count: 818,
  },
  {
    adult: false,
    backdrop_path: "/1awUOlTXQDyDcKUZpxhFBV8MCDX.jpg",
    genre_ids: [28, 16, 14],
    id: 83091,
    original_language: "ja",
    original_title: "聖闘士星矢 神々の熱き戦い",
    overview:
      "In Siberia, Hyōga saves a man that is being attacked. Injured, the man manages only to say something about Asgard. Some days later, Saori, Seiya, Shiryū and Shun are wondering about Hyōga and decide to go to Asgard to investigate. At Valhalla, the Lord of Asgard, Dolbar, says he has not heard of any Hyōga and neither has his right hand, Loki. However, at all times Seiya and the others can feel an evil cosmo emanating from Loki and the other Odin Saints called God Warriors. Shiryū, in particular, notices a familiar cosmo coming from Midgard, a mysterious, masked God Warrior. Dolbar makes it clear that he is trying to take control of both Asgard and the Sanctuary, imprisoning Athena in a strange dimension within the giant statue of Odin. Midgard reveals himself as Hyōga and tries to kill Shiryū to prove himself to Dolbar. Thus, it is the task of the Bronze Saints to defeat Dolbar, Loki and the rest of the God Warriors, to save Athena and Hyōga.",
    popularity: 41.579,
    poster_path: "/zwL4R8y2b18nLe8q0OgSr5vbnnc.jpg",
    release_date: "1988-03-12",
    title: "Saint Seiya: The Heated Battle of the Gods",
    video: false,
    vote_average: 7.479,
    vote_count: 140,
  },
  {
    adult: false,
    backdrop_path: "/c5iPQhmZaq8eC8duhPTN373duEr.jpg",
    genre_ids: [18, 9648, 53],
    id: 890980,
    original_language: "es",
    original_title: "Los renglones torcidos de Dios",
    overview:
      "Alice Gould, a private investigator, pretends to be mentally ill in order to enter a psychiatric hospital and gather evidence for the case she is working on: the death of a patient in unclear circumstances.",
    popularity: 23.042,
    poster_path: "/n3X9tWYFYfE96BoNgtVffuwzQo.jpg",
    release_date: "2022-10-06",
    title: "God's Crooked Lines",
    video: false,
    vote_average: 7.384,
    vote_count: 481,
  },
  {
    adult: false,
    backdrop_path: "/xwEPpPWiH8e0wCCVGmXB30xofYR.jpg",
    genre_ids: [35, 18],
    id: 555285,
    original_language: "en",
    original_title: "Are You There God? It's Me, Margaret.",
    overview:
      "When her family moves from New York City to New Jersey, an 11-year-old girl navigates new friends, feelings, and the beginning of adolescence.",
    popularity: 143.358,
    poster_path: "/yb6UB4WC3znlwU0L4AqMnjR9G9S.jpg",
    release_date: "2023-03-29",
    title: "Are You There God? It's Me, Margaret.",
    video: false,
    vote_average: 7.352,
    vote_count: 64,
  },
  {
    adult: false,
    backdrop_path: "/wsE1ScIiFdKl9RLuaI8pTn4rjxR.jpg",
    genre_ids: [10770, 80, 18, 14, 53, 16],
    id: 51482,
    original_language: "ja",
    original_title: "Death Note: デスノート",
    overview:
      "Yagami Light is an ace student with great prospects, who's bored out of his mind. One day he finds the \"Death Note\": a notebook from the realm of the Death Gods, with the power to kill people in any way he desires. With the Death Note in hand, Light decides to create his perfect world, without crime or criminals. However, when criminals start dropping dead one by one, the authorites send the legendary detective L to track down the killer, and a battle of wits, deception and logic ensues...this was aired on Japanese tv shortly after the death note anime was completed, this special basically re-cuts the first 26 episodes of the series into a two hour movie with some new scenes and dialogue added and the story is seen from ryuk's viewpoint.",
    popularity: 26.592,
    poster_path: "/bB22CJM8arCCRvjFedmH5qtsbHb.jpg",
    release_date: "2007-08-31",
    title: "Death Note Relight 1: Visions of a God",
    video: false,
    vote_average: 8.022,
    vote_count: 247,
  },
];
